name: Metrics

on:
  schedule: [{cron: "0 */12 * * *"}] # runs every 12 hrs
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          user: Pankaj-Bashera
          token: ${{ secrets.METRICS_TOKEN }}

          # 👇 THIS enables calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
